name = agent_x
title = Agent X
description = An Agent Game
author = Just_Visiting
allowed_mapgens = singlenode
disabled_settings = enable_damage, creative_mode, enable_server
map_persistent = true
first_mod = ax_core